### ISSUE TITLE
GPIO only works after toggling "Use Board Pin".

### ISSUE THREAD

**Issue by traveltje2** [vitormhenrique/OctoPrint-Enclosure#33] opened 2017-04-19 21:18 UTC
I have a led connected to GPIO17.
Every time I reboot octoprint I need to toggle the "Use Board Pin #", save it and toggle it again before the GPIO works. After the toggle everything works as expected until a reboot.

**Comment by vitormhenrique** [comment] 2017-04-19 21:26
Ok, I'm a little confused, are you using board pin numbers or bcm? 

By default, this plugin will use BCM pin numbers, if you have if configured any time, for example, even open and saving anything with BCM configured, you won't be able to switch between the BCM and BOARD.

That is why there is a button to "clear gpio mode".

The correct workflow to change between modes is go to the setting screen, clear the GPIO mode, select whatever you want, and save the setting. If you do this, the next time you reboot, the plugin should keep the BOARD number checked and configure it as so....

have you tried this work flow?

**Comment by traveltje2** [comment] 2017-04-19 22:01
Hi, thanks for the fast reply.
I use the normal GPIO pin nr's (tried different pins with the same result.

Your workflow works perfect until a reboot. 
After the reboot I need to follow your workflow again to make it work. 
All other settings are stored and remembered after a reboot (for instance the GPIO17 and name I gave it).

**Comment by vitormhenrique** [comment] 2017-04-19 22:23
So the setting for the BOARD mode is not being remembered after the reboot right?
If so, I might know why, and will fix tonight...

**Comment by traveltje2** [comment] 2017-04-20 01:01
Thats my thought!

**Comment by vitormhenrique** [comment] 2017-05-02 01:10
@traveltje2  I could nor reproduce this issue, by any chance are you using another plugin or any other script on your pi that might be using GPIO? 
I'll add more login information on next release so we can trouble shoot this....

**Comment by vitormhenrique** [comment] 2017-05-14 14:59
@traveltje2 do you still have this issue? I'm going to close this because you did not respond for a while, and I could not reproduce the issue. If needed just reopen the issue and give me more information.

**Closed by vitormhenrique** 2017-05-14 14:59 UTC
Labels: invalid
